### PR TITLE
Bump genext2fs to 1.5.6

### PR DESCRIPTION
**Pull request by endersonmaia**
Related: https://github.com/cartesi/genext2fs/pull/16

### CODE REVIEW

**Review by tuler — COMMENTED** [review]
Package installation failed.

Add changeset for SDK

**Comment by tuler** [comment]
CI still failing

**Comment by endersonmaia** [comment]
> CI still failing

Waiting for the release upstream.

**Comment by endersonmaia** [comment]
> CI still failing

It's green

**Review by tuler — APPROVED** [review]

**Pull request merged**
